# services:
#   nodered:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: mynodered
#     ports:
#       - "1880:1880"
#     volumes:
#       - nodered_data:/data
#     restart: always

# volumes:
#   nodered_data:
version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sword_code_is_3
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  mariadb_data: